apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rondon69/backend:v1  # Replace with your backend Docker image
          ports:
            - containerPort: 6767
          env:
            - name: POSTGRES_URL
              value: "postgresql+asyncpg://abc:abc@postgres:5432/proj"
            - name: MONGO_URL
              value: "mongodb://abc:abc@mongo:27017/chat_db?authSource=admin"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: KAFKA_BROKER
              value: "kafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767
  type: ClusterIP
