version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: abc
      MONGO_INITDB_ROOT_PASSWORD: abc
      MONGO_INITDB_DATABASE: chat_db  # Optional: Automatically create a default database
    ports:
      - "27017:27017"  # Expose MongoDB on the host machine's port 27017
    volumes:
      - mongo_data:/data/db  # Persistent storage for MongoDB data across restarts
  
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose Redis on the host machine's port 6379
    command: redis-server --appendonly yes  # Enable persistence for Redis
    volumes:
      - redis_data:/data/redis  # Persistent storage for Redis data across restarts

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_container
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  backend:
    image: backend  # comment this entire thing incase of local development
    container_name: backend
    environment:
      MONGO_URL: mongodb://abc:abc@mongo_container:27017/chat_db?authSource=admin
      POSTGRES_URL: postgresql+asyncpg://abc:abc@postgres_container:5432/proj
      REDIS_URL: redis://redis:6379/0
      KAFKA_BROKER: kafka:9092
    ports:
      - "6767:6767"
    depends_on:
      - mongo
      - postgres
      - redis
      - kafka
volumes:
  postgres_data:
  mongo_data:
  redis_data:
