version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: abc
      MONGO_INITDB_ROOT_PASSWORD: abc
      MONGO_INITDB_DATABASE: chat_db  # Optional: Automatically create a default database
    ports:
      - "27017:27017"  # Expose MongoDB on the host machine's port 27017
    volumes:
      - mongo_data:/data/db  # Persistent storage for MongoDB data across restarts
  
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose Redis on the host machine's port 6379
    command: redis-server --appendonly yes  # Enable persistence for Redis
    volumes:
      - redis_data:/data/redis  # Persistent storage for Redis data across restarts


<<<<<<< HEAD
  backend:
    image: backend  # comment this entire thing incase of local development
    container_name: backend
    environment:
      MONGO_URL: mongodb://abc:abc@mongo_container:27017/chat_db?authSource=admin
      POSTGRES_URL: postgresql+asyncpg://abc:abc@postgres_container:5432/proj
    ports:
      - "6767:6767"
    depends_on:
      - mongo
      - postgres
=======
  # fastapi:
  #   build:
  #     context: .
  #   container_name: fastapi_container
  #   depends_on:
  #     - postgres
  #     - mongo
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     POSTGRES_URL: postgres://myuser:mypassword@postgres:5432/mydb
  #     MONGO_URL: mongodb://mongo:27017
  #     REDIS_URL: redis://redis:6379/0

>>>>>>> f293c4e (Added Redis)
volumes:
  postgres_data:
  mongo_data:
  redis_data:
