version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: abc
      MONGO_INITDB_ROOT_PASSWORD: abc
      MONGO_INITDB_DATABASE: chat_db  # Optional: Automatically create a default database
    ports:
      - "27017:27017"  # Expose MongoDB on the host machine's port 27017
    volumes:
      - mongo_data:/data/db  # Persistent storage for MongoDB data across restarts

  backend:
    image: backend  # comment this entire thing incase of local development
    container_name: backend
    environment:
      MONGO_URL: mongodb://abc:abc@mongo_container:27017/chat_db?authSource=admin
      POSTGRES_URL: postgresql+asyncpg://abc:abc@postgres_container:5432/proj
    ports:
      - "6767:6767"
    depends_on:
      - mongo
      - postgres
volumes:
  postgres_data:
  mongo_data:
