version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: proj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: abc
      MONGO_INITDB_ROOT_PASSWORD: abc
      MONGO_INITDB_DATABASE: chat_db  # Optional: Automatically create a default database
    ports:
      - "27017:27017"  # Expose MongoDB on the host machine's port 27017
    volumes:
      - mongo_data:/data/db  # Persistent storage for MongoDB data across restarts

  # fastapi:
  #   build:
  #     context: .
  #   container_name: fastapi_container
  #   depends_on:
  #     - postgres
  #     - mongo
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     POSTGRES_URL: postgres://myuser:mypassword@postgres:5432/mydb
  #     MONGO_URL: mongodb://mongo:27017

volumes:
  postgres_data:
  mongo_data:
